export const demoVehicles = [
  {
    vin: "DEMO1234567890001",
    year: 2023,
    make: "Ferrari",
    model: "SF90 Stradale",
    mileage: 2500,
    color: "Rosso Corsa",
    price: 598000,
    condition: "Excellent",
    description: "Stunning hybrid hypercar with 986 horsepower. Full carbon fiber package, racing seats, and front lift system. Single owner, always garaged.",
    photos: ["/attached_assets/stock_images/red_ferrari_supercar_898393ee.jpg"],
    status: "available",
    featured: true,
    isDemo: true,
  },
  {
    vin: "DEMO1234567890002",
    year: 2022,
    make: "Lamborghini",
    model: "Aventador LP 780-4 Ultimae",
    mileage: 1200,
    color: "Verde Mantis",
    price: 725000,
    condition: "Excellent",
    description: "The final edition Aventador. Just 350 coupes produced worldwide. Full PPF, ceramic coating, and all original documentation.",
    photos: ["/attached_assets/stock_images/green_lamborghini_ex_ff9fd3a5.jpg"],
    status: "available",
    featured: true,
    isDemo: true,
  },
  {
    vin: "DEMO1234567890003",
    year: 2024,
    make: "Porsche",
    model: "911 GT3 RS",
    mileage: 850,
    color: "Python Green",
    price: 325000,
    condition: "Excellent",
    description: "Track-focused perfection. Weissach package, PDK transmission, front axle lift, and full bucket seats. MSRP was $290k.",
    photos: ["/attached_assets/stock_images/silver_porsche_911_s_ea338d8e.jpg"],
    status: "available",
    featured: false,
    isDemo: true,
  },
  {
    vin: "DEMO1234567890004",
    year: 2021,
    make: "McLaren",
    model: "765LT Spider",
    mileage: 3200,
    color: "Papaya Spark",
    price: 425000,
    condition: "Excellent",
    description: "One of only 765 produced. MSO carbon fiber exterior pack, Senna carbon seats, and track telemetry system.",
    photos: ["/attached_assets/stock_images/orange_mclaren_super_f4b13162.jpg"],
    status: "available",
    featured: false,
    isDemo: true,
  },
  {
    vin: "DEMO1234567890005",
    year: 2023,
    make: "Rolls-Royce",
    model: "Cullinan Black Badge",
    mileage: 5800,
    color: "Black Diamond",
    price: 485000,
    condition: "Excellent",
    description: "Ultimate luxury SUV. Starlight headliner, rear theater configuration, champagne fridge, and bespoke audio system.",
    photos: ["/attached_assets/stock_images/black_rolls_royce_lu_51d802d4.jpg"],
    status: "available",
    featured: true,
    isDemo: true,
  },
  {
    vin: "DEMO1234567890006",
    year: 2022,
    make: "Bentley",
    model: "Continental GT Speed",
    mileage: 8500,
    color: "Glacier White",
    price: 275000,
    condition: "Excellent",
    description: "The most powerful Continental ever. Mulliner driving spec, rotating display, and Naim audio system.",
    photos: ["/attached_assets/stock_images/white_bentley_luxury_c3802c58.jpg"],
    status: "pending_sale",
    featured: false,
    isDemo: true,
  },
];

export const demoConsignments = [
  {
    vin: "DEMO9876543210001",
    year: "2020",
    make: "Ferrari",
    model: "488 Pista",
    mileage: "4200",
    color: "Bianco Avus",
    condition: "Excellent",
    accidentHistory: "No accidents",
    description: "Fully loaded 488 Pista with racing stripes and carbon fiber everywhere.",
    firstName: "Michael",
    lastName: "Sterling",
    email: "demo.seller1@example.com",
    phone: "+15551234567",
    photos: [],
    salvageTitle: false,
    mechanicalIssues: null,
    lienStatus: false,
    ownershipConfirmed: true,
    agreementAccepted: true,
    termsAccepted: true,
    status: "pending",
    isDemo: true,
  },
  {
    vin: "DEMO9876543210002",
    year: "2019",
    make: "Lamborghini",
    model: "Huracan Performante",
    mileage: "7800",
    color: "Grigio Lynx",
    condition: "Excellent",
    accidentHistory: "No accidents",
    description: "Performance package with ALA aerodynamics system.",
    firstName: "Jennifer",
    lastName: "Blackwood",
    email: "demo.seller2@example.com",
    phone: "+15559876543",
    photos: [],
    salvageTitle: false,
    mechanicalIssues: null,
    lienStatus: false,
    ownershipConfirmed: true,
    agreementAccepted: true,
    termsAccepted: true,
    status: "under_review",
    isDemo: true,
  },
];

export const demoTestimonials = [
  {
    customerName: "James Richardson",
    customerLocation: "Beverly Hills, CA",
    vehicleSold: "2021 Ferrari Roma",
    rating: 5,
    content: "Incredible experience from start to finish. They handled everything professionally and got me top dollar for my Roma. Highly recommended for anyone selling a luxury vehicle.",
    featured: true,
    approved: true,
    isDemo: true,
  },
  {
    customerName: "Sarah Mitchell",
    customerLocation: "Miami, FL",
    vehicleSold: "2020 Lamborghini Urus",
    rating: 5,
    content: "The team was knowledgeable, responsive, and made the entire consignment process seamless. My Urus sold within weeks at an excellent price.",
    featured: true,
    approved: true,
    isDemo: true,
  },
  {
    customerName: "Robert Chen",
    customerLocation: "New York, NY",
    vehicleSold: "2022 Porsche 911 Turbo S",
    rating: 5,
    content: "As a first-time seller, I was nervous about the process. The staff walked me through every step and exceeded my expectations. Will definitely use again.",
    featured: false,
    approved: true,
    isDemo: true,
  },
];

export const demoBuyerInquiries = [
  {
    buyerName: "David Thompson",
    buyerPhone: "+15551112222",
    buyerEmail: "demo.buyer1@example.com",
    message: "Very interested in the SF90. Is the price negotiable? I'm ready to move quickly.",
    interestType: "purchase",
    buyTimeline: "immediate",
    hasTradeIn: false,
    financingPreference: "cash",
    contactPreference: "phone",
    bestTimeToContact: "afternoon",
    pipelineStage: "new",
    isDemo: true,
  },
  {
    buyerName: "Amanda Foster",
    buyerPhone: "+15553334444",
    buyerEmail: "demo.buyer2@example.com",
    message: "Looking at the Aventador Ultimae. Can you provide Carfax and maintenance records?",
    interestType: "purchase",
    buyTimeline: "this_week",
    hasTradeIn: true,
    financingPreference: "cash",
    contactPreference: "email",
    bestTimeToContact: "morning",
    pipelineStage: "contacted",
    isDemo: true,
  },
  {
    buyerName: "Christopher Wright",
    buyerPhone: "+15555556666",
    buyerEmail: "demo.buyer3@example.com",
    message: "I'd like to schedule a viewing of the GT3 RS. Available this weekend?",
    interestType: "test_drive",
    buyTimeline: "this_month",
    hasTradeIn: false,
    financingPreference: "financing",
    contactPreference: "phone",
    bestTimeToContact: "evening",
    pipelineStage: "scheduled",
    isDemo: true,
  },
  {
    buyerName: "Elizabeth Monroe",
    buyerPhone: "+15557778888",
    buyerEmail: "demo.buyer4@example.com",
    message: "We've agreed on terms. Ready to proceed with purchase of the Cullinan.",
    interestType: "purchase",
    buyTimeline: "immediate",
    hasTradeIn: true,
    financingPreference: "cash",
    contactPreference: "phone",
    bestTimeToContact: "afternoon",
    pipelineStage: "negotiating",
    isDemo: true,
  },
];
